services:
  postgresql:
    image: postgres
    container_name: ogl
    ports:
      - "5433:5432"
    environment:  
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dkfll
      - POSTGRES_DATABASE=smartappdb
    command: postgres
    restart: always

  redis:
    image: redis
    container_name: redis-oogl
    ports:
      - "6379:6379"