services:
  postgresql:
    image: postgres
    container_name: ogl
    ports:
      - "5433:5432"
    environment:  
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dkfll
      - POSTGRES_DATABASE=smartappdb
    command: postgres
    restart: always

  redis:
    image: redis:7-alpine
    container_name: ogl-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network
    restart: unless-stopped